name = "FieldMetadata"
uuid = "bf96fef3-21d2-5d20-8afa-0e7d4c32a885"
authors = ["Rafael Schouten <rafaelschouten@gmail.com>"]
version = "0.0.3"

[extras]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Parameters", "REPL", "Markdown", "Test"]
